export const WIZARDS = [
  {
    key: 'wizard-emerald',
    name: 'Erevan',
    art: '/wizard-emerald.webp',
    alt: 'Erevan the Emerald Wizard',
    color1: 'oklch(0.32 0.04 166)',
    color2: 'oklch(0.46 0.06 164.49)',
    color3: 'oklch(0.61 0.08 154.05)',
    offsets: { x: '-70%', y: '53%', scale: '4.3' },
    bio: `In a realm of ancient lore and mystical arts, there existed Erevan the Emerald, a wizard of great renown. Cloaked in robes of forest green, his silver hair flowed like a shimmering waterfall. Erevan, with piercing emerald eyes, possessed a profound understanding of the arcane and a mastery over emeralds.
    <br /><br />
    These precious gems yielded to his will, channeling their energies for healing and growth. From sprouts to entire forests, Erevan's emerald sorcery breathed life and harmony. Legends of his power spread, and seekers of solace sought his guidance.`,
  },
  {
    key: 'wizard-ruby',
    name: 'Roderick',
    art: '/wizard-ruby.webp',
    alt: 'Roderick the Ruby Wizard',
    color1: 'oklch(0.27 0.06 23.81)',
    color2: 'oklch(0.48 0.13 38.12)',
    color3: 'oklch(0.55 0.13 33.78)',
    offsets: { x: '-70%', y: '53%', scale: '4.3' },
    pendant: '/ruby-pendant.webp',
    bio: `In a realm ablaze with magic's fervor, Roderick the Ruby emerged as a formidable wizard. Clad in fiery robes, his eyes held untamed power. With mastery over rubies, he commanded their fiery essence. Flames danced at his touch, creating and destroying with equal intensity. Legends whispered of his prowess, and seekers of power sought his fiery enchantments. Roderick, the embodiment of the ruby's might, left a scorching legacy wherever he tread, forever entwined with the realm's tapestry of magic.`,
  },
  {
    key: 'Astrid',
    name: 'Astrid',
    art: '/wizard-amber.webp',
    alt: 'Astrid the Amber',
    color1: 'oklch(0.38 0.07 93.68)',
    color2: 'oklch(0.67 0.07 90.08)',
    color3: 'oklch(0.6 0.11 81.32)',
    offsets: { x: '-50%', y: '30%', scale: '3' },
    bio: `In the realm of ancient wisdom and golden serenity, Astrid the Amber, a revered wizard, possessed a deep connection to the mystical energies of amber stones. With a gentle touch, she harnessed their healing power, restoring spirits and revealing forgotten truths. Seekers of balance and solace sought her guidance, drawn to her tranquil aura. Astrid, a beacon of inner radiance, left a trail of warmth and illumination as she journeyed through the realms, forever intertwined with the transformative magic of amber.`,
  },
  {
    key: 'Soren',
    name: 'Soren',
    art: '/wizard-sapphire.webp',
    alt: 'Soren the Sapphire',
    color1: 'oklch(0.29 0.04 262.83)',
    color2: 'oklch(0.63 0.04 223.54)',
    color3: 'oklch(0.59 0.1 231.78)',
    offsets: { x: '-70%', y: '15%', scale: '3.5' },
    bio: `In the realm of sky and sea, Soren the Sapphire, an aged wizard, possessed unmatched wisdom. Clad in midnight robes, his eyes held ancient brilliance. With a thought, he harnessed sapphires' clarity, unveiling cosmic mysteries. Seekers of truth sought his guidance, drawn to his serene power. Soren, a symbol of wisdom, left trails of starlit magic as he journeyed, forever connected to the boundless secrets of sapphires.`,
  },
  {
    key: 'Arion',
    name: 'Arion',
    art: '/wizard-amethyst.webp',
    alt: 'Arion the Amethyst',
    color1: 'oklch(0.27 0.03 319.13)',
    color2: 'oklch(0.49 0.11 313.41)',
    color3: 'oklch(0.55 0.07 311.32)',
    offsets: { x: '-51%', y: '58%', scale: '4.25' },
    bio: `In a realm veiled in ancient mysticism, Arion the Amethyst emerged as a revered wizard. Clad in twilight robes, his eyes held timeless wisdom. With a touch, he summoned the tranquil power of amethyst, unraveling cosmic mysteries and restoring balance. Seekers of truth sought his counsel, drawn to his radiant presence. Arion, a symbol of ethereal harmony, left trails of twilight shimmer as he traversed the realms, forever connected to the transformative magic of amethyst.`,
  },
  {
    key: 'Paridian',
    name: 'Paridian',
    art: '/wizard-peridot.webp',
    alt: 'Paridian the Peridot',
    color1: 'oklch(0.32 0.03 102.4)',
    color2: 'oklch(0.52 0.02 118.79)',
    color3: 'oklch(0.8 0.05 119.43)',
    offsets: { x: '-51%', y: '74%', scale: '4' },
    bio: `In the ancient realms where wisdom and enchantment entwined, there lived a figure whose name echoed through the ages: Paridian the Peridot. An elder wizard of boundless knowledge, he was attuned to the mystical essence of the emerald-hued gem. Clad in forest-green robes, his eyes reflected the depths of ancient forests. With a touch, he communed with nature and wielded the peridot's vibrant energy to restore harmony and nurture life. Seekers of wisdom sought his counsel, drawn to his tranquil presence. Paridian, a symbol of enduring wisdom, left trails of emerald radiance as he traversed the realms, forever connected to the transformative magic of the peridot.`,
  },
  {
    key: 'Osgar',
    name: 'Osgar',
    art: '/wizard-onyx.webp',
    alt: 'Osgar the Onyx',
    color1: 'oklch(0.23 0.01 77.97)',
    color2: 'oklch(0.33 0.01 0)',
    color3: 'oklch(0.57 0.01 82.22)',
    offsets: { x: '-30%', y: '96%', scale: '5.5' },
    bio: `In the ancient realms, a figure emerged whose name instilled fear: Osgar the Onyx. Once a renowned wizard, his insatiable greed for power corrupted his noble intentions. Clad in dark robes, his eyes gleamed with malice. Osgar's quest to harvest gemstone power consumed him, turning him into a cruel tyrant. The lands withered under his influence as he terrorized innocents and commanded dark creatures. Osgar, the fallen wizard, became a cautionary tale of unchecked greed and the darkness it spawns. The realms united to confront his malevolence and restore balance, vowing never to succumb to such temptation again.`,
  },
];
