export const WIZARDS = [
  {
    key: 'wizard-emerald',
    name: 'Erevan',
    art: '/wizard-emerald.webp',
    alt: 'Erevan the Emerald Wizard',
    color1: 'oklch(0.32 0.04 166)',
    color2: 'oklch(0.46 0.06 164.49)',
    color3: 'oklch(0.61 0.08 154.05)',
    offsets: { x: '-70%', y: '53%', scale: '4.3' },
    bio: `In a realm of ancient lore and mystical arts, there existed Erevan the Emerald, a wizard of great renown. Cloaked in robes of forest green, his silver hair flowed like a shimmering waterfall. Erevan, with piercing emerald eyes, possessed a profound understanding of the arcane and a mastery over emeralds.
    <br /><br />
    These precious gems yielded to his will, channeling their energies for healing and growth. From sprouts to entire forests, Erevan's emerald sorcery breathed life and harmony. Legends of his power spread, and seekers of solace sought his guidance.`,
  },
  {
    key: 'wizard-ruby',
    name: 'Roderick',
    art: '/wizard-ruby.webp',
    alt: 'Roderick the Ruby Wizard',
    color1: 'oklch(0.27 0.06 23.81)',
    color2: 'oklch(0.48 0.13 38.12)',
    color3: 'oklch(0.55 0.13 33.78)',
    offsets: { x: '-70%', y: '53%', scale: '4.3' },
    bio: `In a realm ablaze with magic's fervor, Roderick the Ruby emerged as a formidable wizard. Clad in fiery robes, his eyes held untamed power. With mastery over rubies, he commanded their fiery essence. Flames danced at his touch, creating and destroying with equal intensity. Legends whispered of his prowess, and seekers of power sought his fiery enchantments. Roderick, the embodiment of the ruby's might, left a scorching legacy wherever he tread, forever entwined with the realm's tapestry of magic.`,
  },
  {
    key: 'wizard-amber',
    name: 'Amber',
    art: '/wizard-amber.webp',
    alt: 'Amber Wizard',
    color1: 'oklch(0.38 0.07 93.68)',
    color2: 'oklch(0.67 0.07 90.08)',
    color3: 'oklch(0.6 0.11 81.32)',
    offsets: { x: '-50%', y: '30%', scale: '3' },
  },
  {
    key: 'wizard-sapphire',
    name: 'Sapphire',
    art: '/wizard-sapphire.webp',
    alt: 'Sapphire Wizard',
    color1: 'oklch(0.29 0.04 262.83)',
    color2: 'oklch(0.63 0.04 223.54)',
    color3: 'oklch(0.59 0.1 231.78)',
    offsets: { x: '-70%', y: '15%', scale: '3.5' },
  },
  {
    key: 'wizard-amethyst',
    name: 'Amethyst',
    art: '/wizard-amethyst.webp',
    alt: 'Amethyst Wizard',
    color1: 'oklch(0.27 0.03 319.13)',
    color2: 'oklch(0.49 0.11 313.41)',
    color3: 'oklch(0.55 0.07 311.32)',
    offsets: { x: '-51%', y: '58%', scale: '4.25' },
  },
  {
    key: 'wizard-peridot',
    name: 'Peridot',
    art: '/wizard-peridot.webp',
    alt: 'Peridot Wizard',
    color1: 'oklch(0.32 0.03 102.4)',
    color2: 'oklch(0.52 0.02 118.79)',
    color3: 'oklch(0.8 0.05 119.43)',
    offsets: { x: '-51%', y: '74%', scale: '4' },
  },
  {
    key: 'wizard-onyx',
    name: 'Onyx',
    art: '/wizard-onyx.webp',
    alt: 'Onyx Wizard',
    color1: 'oklch(0.23 0.01 77.97)',
    color2: 'oklch(0.33 0.01 0)',
    color3: 'oklch(0.57 0.01 82.22)',
    offsets: { x: '-30%', y: '96%', scale: '5.5' },
  },
];
